### PR TITLE
GZIP support

### PR DESCRIPTION
**Pull request by arkhamvm**

### CODE REVIEW

**Comment by arkhamvm** [comment]
@cebe can you take a look please?
In my case it reduces network load by 94%.

**Comment by cebe** [comment]
Thanks for the contribution. Can you please add a flag that allows to enable/disable the feature? Default could be true.

**Comment by arkhamvm** [comment]
@cebe Done.

**Comment by arkhamvm** [comment]
@cebe, is any other workaround required?

**Review by cebe — APPROVED** [review]

**Comment by cebe** [comment]
Thank you!

**Pull request merged**
